### PR TITLE
Merged association group fix with branch master changes

### PR DESCRIPTION
**Pull request by apwelsh**
This change is my prior pull request to fix the association group configurations only performed all necessary merge operations to sync this with master.

Issue to note, not all drivers are consistent in logging.  Most use logEnable, but some use infoEnable and debugEnable instead, and I believe two auto-disable the login after 30 minutes (iirc).

I hope you can merge this pull request this time.  I really need to association groups to work in the devices w/o having to rely on the z-wave association tool.  This version support the z-wave association tool as the last pull request was updated to do.

### CODE REVIEW

**Comment by apwelsh** [comment]
Hey @InovelliUSA, any plans to merge this fix?  Eric seemed to show substantial interest in the fix, but it has been waiting  for a while now (considering the original change, and now the updated change to reconcile the merge conflicts).  I use this version of the drivers on my system, and would like to be able to pull updates from github rather than manually manage updates.

**Comment by InovelliUSA** [comment]
Yeah, we are super interested in merging these changes. I just haven't had a chance to test the different devices. Just wondering which devices you have had a chance to test?

**Comment by apwelsh** [comment]
I have been using the NZW-30, NZW-31 (both with and without scenes)? and LZW-30 (black).  I will soon test the LZW-31 (red) when I airing them up this weekend.  The solution for all of them was the same, so I don’t anticipate issue, still it was not possible to scenario test them all.

**Comment by apwelsh** [comment]
I just went through another round of merges on my cloned repo to update my changes with the latest master branch if you have any issues with this, let me know.

**Comment by InovelliUSA** [comment]
Ok, I think I am just going to go for it on all these file changes because I don't have time to check them all.

I know you made it compatible with the previous version of ZAT, but is there anything else I should know?

**Comment by InovelliUSA** [comment]
Looks like things are working except for the "maxAssociationGroup" method. The command was not being sent. I changed it from:

zwave.associationV2.associationGroupingsGet()

to

sendHubCommand(new hubitat.device.HubAction(command(zwave.associationV2.associationGroupingsGet()), hubitat.device.Protocol.ZWAVE )) // execute the update immediately

Which seemed to work.

**Comment by apwelsh** [comment]
Thanks!  There were changes since and I cannot test more than the 4 device types I have.

**Comment by apwelsh** [comment]
Happy to help

**Pull request merged**
