### PR TITLE
LZW41 and LZW42 fixes

### PR DESCRIPTION
**Pull request by djdizzyd**
- Added color pre-staging option
- Added power restored memory configuration
- Added debug logging configuration
- Fixed color setting 
- Fixed color temperature setting 
- Fixed reporting 
- Removed SmartThings related code
- Added importURL
- Added color name
- Added firmware version reporting
- Added ColorMode capability for proper scene capture on multi-color

### CODE REVIEW

**Comment by djdizzyd** [comment]
@InovelliUSA Poke

**Comment by sgrayban** [comment]
They are at CES.

**Comment by djdizzyd** [comment]
👆Probably good that they haven’t gotten to this pull request yet.. But I think it is finally all worked out

**Comment by djdizzyd** [comment]
24 hours and no bug reports.. Also haven't noticed any on mine..

**Comment by djdizzyd** [comment]
Forum threads involving these changes:

https://community.hubitat.com/t/release-modified-inovelli-bulbs-drivers/30922?u=bcopeland

https://community.inovelli.com/t/hubitat-bulbs-lzw41-and-lzw42-drivers/1654?u=bcopeland

**Comment by TejasAntani** [comment]
Did this end up also making it to the SmartThings side? Having a lot of issues with these bulbs

**Pull request merged**
