### PR TITLE
Added dimming speed to on and off commands for the LZW42

### PR DESCRIPTION
**Pull request by npk22**
Added dimming speed parameter and dimming speed to the on off commands for the LZW42.

### CODE REVIEW

**Comment by npk22** [comment]
Updated if statement for deleting child devices for Inovelli Switch Red Series LZW30-SN

**Comment by InovelliUSA** [comment]
So I actually intended the else if statement to operate this way. Basically if you haven't set any of the notification options or you set the effect option to "off" it will delete the device. 

In Hubitat it seems like once you set these notification options there is not an option to choose "No selection". So technically the first four statements won't ever be true when the child exists anyway so the check to see if the user set the effect to 0 is going to be the determining factor.

**Comment by npk22** [comment]
I agree. I like the design where you can select "no selection" and it will delete the child. Having to find the "off" option makes it slightly more confusing for user when trying to delete a child.

The ANDing of the null checks with the rest of the elseif statements made this always false for me on child device that was already configured. Matching the [dimmer driver](https://github.com/InovelliUSA/Hubitat/blob/master/Drivers/inovelli-dimmer-red-series-lzw31-sn.src/inovelli-dimmer-red-series-lzw31-sn.groovy#L701) fixed the issue where I was unable to delete children.

**Comment by InovelliUSA** [comment]
Oh, I see. I messed up on the ON / OFF driver. Oops.

**Pull request merged**
