### PR TITLE
fixed parent association issue causing a 404 when creating child app

### PR DESCRIPTION
**Pull request by sgrayban**
For some reason Hubitat didn't like the original code. After I re-added the parent line it worked. Maybe some odd encoding happened when it was pushed is all I can think of.

### CODE REVIEW

**Comment by apwelsh** [comment]
Would t a more appropriate change description be that you removed the icon url paths?  Those are the only changes I see.

**Comment by sgrayban** [comment]
Nope.. read my comment above

**Comment by apwelsh** [comment]
Right.  Except the changes tab does not show any changes regarding parent, it only show icon url changes and a change to readme.md. If there is a bug I should fix on my he, I would like to, which is why I commented

**Comment by sgrayban** [comment]
Umm when I re-added the parent line in the Z-Wave Association code, specifically line 28, and saved it in my HE the app worked. So like I commented above it must have been some odd encoding on Eric's end when he pushed the code.

**Comment by apwelsh** [comment]
Ah.  So I can ignore this one.  That line was not an issue on my He, and the diff does not show that line being changed.

**Comment by sgrayban** [comment]
Say Eric, by mistake, did not save the file encoded in UTF-8 but instead with windows LB the encoding or some other obscure encoding like BOM, byte order mark, doing a import via the import url it would transfer that encoding thus breaking in HE... Now if you did a straight copy/paste most likely that wouldn't be a issue because the copy/paste is encoded correctly.

**Comment by apwelsh** [comment]
Yup I get it now.

**Comment by sgrayban** [comment]
removing PR

**Pull request closed without merging**
